services:
  imtiaz_mart:
    build:
      context: ./Imtiaz_mart/online_imtiaz_mart
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - Imtiaz_mart
    container_name: imtiaz_mart

  products:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./product/.env
    networks:
      - Imtiaz_mart
    container_name: product

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./user/.env
    networks:
      - Imtiaz_mart
    container_name: user-service

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./auth/.env
    networks:
      - Imtiaz_mart
    container_name: auth  

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./order/.env
    networks:
      - Imtiaz_mart
    container_name: order

  db:
    image: postgres:14
    container_name: postgresDatabase
    environment:
      - POSTGRES_USER=online_imtiaz_mart
      - POSTGRES_PASSWORD=G8QmA%24GAX4yKhZG
      - POSTGRES_DB=Imtiaz_mart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - Imtiaz_mart

networks:
  Imtiaz_mart:
    driver: bridge

volumes:
  pgdata:
    driver: local
